### ISSUE TITLE
remove lightgbm support?

### ISSUE THREAD

**Issue by simonpcouch** [rstudio/bundle#24]
lightgbm currently has a dedicated bundling method, but will not need one when support for serialization via `saveRDS` + `readRDS` in the dev R package version (implemented in https://github.com/microsoft/LightGBM/pull/4685) hits CRAN. It may be worth removing the lightgbm support before our initial CRAN release so we don't need to work through a deprecation cycle for those bundlers.

Their release timeline here: https://github.com/microsoft/LightGBM/issues/5153

Related to tidymodels/bonsai#44—thanks for the note, @jameslamb. :)

**Comment by juliasilge** [comment]
This sounds like a good plan; let's remove the lightGBM support before the initial CRAN release. 👍
