### ISSUE TITLE
Do we need a helper like `has_bundler()`?

### ISSUE THREAD

**Issue by simonpcouch** [rstudio/bundle#29]
The `has_bundler()` helper intends to help answer the question "will calling `bundle()` on `x` make use of any native serialization methods?"

e.g., `has_bundler(x)` would be `TRUE` is `x` was an xgboost fit or a workflow with a `step_umap` in its recipe, but `FALSE` if `x` is a workflow with an `lm` and a formula recipe. 

I thought this sort of machinery would be useful for navigating the butcher/bundle interaction, but it turns out that butchering before bundling seems to always be fine, at least so far (#28).

I'm no longer sure whether we need a helper like `has_bundler()`.🤔

**Comment by juliasilge** [comment]
I think that this would not be something a user would typically need to do, and for more developer-type tasks, we can check if we have specific `methods()`.

What would you think about removing this from the initial release? We could add a [vignette like the one for butcher](https://github.com/tidymodels/butcher/blob/main/vignettes/available-axe-methods.Rmd) that makes a nice table of everything that is supported.

**Comment by simonpcouch** [comment]
On board! I'll:

* [ ] close #30 
* [ ] put in a PR to remove the helper
* [ ] put in a PR to add a vignette like the one you've described
