### ISSUE TITLE
Wanted to call your attention to a typo

### ISSUE THREAD

**Issue by hammao** [rstudio/bundle#48]
In the example (manual) accompanying the bundle package. There is a typo where you try to unbundle ![image](https://user-images.githubusercontent.com/7891105/190851314-ebd56bd3-7945-467f-93c7-c9ae1ffafe26.jpeg)

**Comment by juliasilge** [comment]
Thanks for taking a look @hammao! I think I need a bit more info here; is this from the [blog post](https://www.tidyverse.org/blog/2022/09/bundle-0-1-0/)? What are you seeing that you think is a typo?

**Comment by juliasilge** [comment]
Let us know if you run into problems! 🙌
